name: HTML Validation

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  html:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - uses: Cyb3r-Jak3/html5validator-action@v7.2.0
        with:
          root: .
